// Player Register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe",
	"email": "john@example.com",
    "password": "password123"
}

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe2",
	"email": "john2@example.com",
    "password": "password123"
}

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe3",
	"email": "john3@example.com",
    "password": "password123"
}

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe4",
	"email": "john4@example.com",
    "password": "password123"
}

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe5",
	"email": "john5@example.com",
    "password": "password123"
}

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe6",
	"email": "john6@example.com",
    "password": "password123"
}

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe7",
	"email": "john7@example.com",
    "password": "password123"
}

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe8",
	"email": "john8@example.com",
    "password": "password123"
}

###


// Delete Player

###
// Create Tournament
POST http://localhost:8080/tournaments/
Content-Type: application/json

{
    "name": "Test_Tourney",
    "description": "My first ever Tournament for 8 players",
    "maxPlayers": "8",
    "minElo": "100",
    "type": "SINGLE_KNOCKOUT",
    "startDate": "2024-09-12T05:09:10Z",
    "endDate": "2024-10-12T05:09:10Z"
}

// List Tournament


// Update Tournament


// Delete Tournament
