// Player Register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe",
	"email": "john@gmail.com",
    "password": "password123"
}

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe2",
	"email": "john2@example.com",
    "password": "password123"
}

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe3",
	"email": "john3@example.com",
    "password": "password123"
}

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe4",
	"email": "john4@example.com",
    "password": "password123"
}

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe5",
	"email": "john5@example.com",
    "password": "password123"
}

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe6",
	"email": "john6@example.com",
    "password": "password123"
}

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe7",
	"email": "john7@example.com",
    "password": "password123"
}

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "john_doe8",
	"email": "john8@example.com",
    "password": "password123"
}

###
# POST http://localhost:8080/auth/register
# Content-Type: application/json

# {
#     "name": "john_doe9",
# 	"email": "john9@example.com",
#     "password": "password123"
# }

# ###
# POST http://localhost:8080/auth/register
# Content-Type: application/json

# {
#     "name": "john_doe10",
# 	"email": "john10@example.com",
#     "password": "password123"
# }

# ###


// Delete Player

###
// Create Tournament
POST http://localhost:8080/tournaments/
Content-Type: application/json

{
    "name": "Test_Tourney",
    "description": "My first ever Tournament for 8 players",
    "maxPlayers": "8",
    "minElo": "100",
    "type": "SINGLE_KNOCKOUT",
    "startDate": "2024-10-12T05:09:10Z",
    "endDate": "2024-11-13T05:09:10Z"
}
###

# POST http://localhost:8080/tournaments/
Content-Type: application/json

{
    "name": "Test_Tourney",
    "description": "My first ever Tournament for 8 players",
    "maxPlayers": "16",
    "minElo": "100",
    "type": "SINGLE_KNOCKOUT",
    "startDate": "2024-09-12T05:09:10Z",
    "endDate": "2024-10-12T05:09:10Z"
}
###
// Add player to Tournament using email
POST http://localhost:8080/tournaments/1/add
Content-Type: application/json

{
    "email": "john@gmail.com"
}

###
// Add player to Tournament using Id
POST http://localhost:8080/tournaments/1/add/2
Content-Type: application/json

{
    
}

###
POST http://localhost:8080/tournaments/1/add/3
Content-Type: application/json

{
    
}
###
POST http://localhost:8080/tournaments/1/add/4
Content-Type: application/json

{
    
}
###
POST http://localhost:8080/tournaments/1/add/5
Content-Type: application/json

{
    
}
###
POST http://localhost:8080/tournaments/1/add/6
Content-Type: application/json

{
    
}
###
POST http://localhost:8080/tournaments/1/add/7
Content-Type: application/json

{
    
}
###
POST http://localhost:8080/tournaments/1/add/8
Content-Type: application/json

{
    
}
# ###
# POST http://localhost:8080/tournaments/1/add/9
# Content-Type: application/json

# {
    
# }
# ###
# POST http://localhost:8080/tournaments/1/add/10
# Content-Type: application/json

# {
    
# }
# ###

###
// List Tournament


// Update Tournament


// Delete Tournament


// List Matches
GET http://localhost:8080/match/list/1
Content-Type: application/json

{
    
}
###

// Start Tournament
POST http://localhost:8080/tournaments/1/start
Content-Type: application/json

{

}


###

// update match outcome

POST http://localhost:8080/match/1/update
Content-Type: application/json

{
    "outcome" : "1.0"
}

###
POST http://localhost:8080/match/2/update
Content-Type: application/json

{
"outcome" : "1.0"
}

###
POST http://localhost:8080/match/3/update
Content-Type: application/json

{
  "outcome" : "0"
}

###
POST http://localhost:8080/match/4/update
Content-Type: application/json

{
  "outcome" : "0"
}


###


// move to round 2

POST http://localhost:8080/tournaments/1/nextround
Content-Type: application/json

{

}
###
// update matches 5 and 6
POST http://localhost:8080/match/5/update
Content-Type: application/json

{
  "outcome" : "0"
}

###
POST http://localhost:8080/match/6/update
Content-Type: application/json

{
  "outcome" : "1"
}


###
// Move to round 3
POST http://localhost:8080/tournaments/1/nextround
Content-Type: application/json

{

}
###
// update match 7
POST http://localhost:8080/match/7/update
Content-Type: application/json

{
  "outcome" : "1"
}
###
// try to go round 4 (fail as only 1 player left, the winner)
POST http://localhost:8080/tournaments/1/nextround
Content-Type: application/json

{

}

